// Checked-in copy of the type references Next.js writes into the generated
// `next-env.d.ts` at the repo root.
//
// That generated file is gitignored (.gitignore) but listed in tsconfig's
// `include`, so on a fresh clone it does not exist yet and `npm run type-check`
// fails with TS2307 on every static image import (`@/public/providers/*.png`),
// which `next/image-types/global` is what declares. Since `.husky/pre-push`
// runs exactly `npm run type-check && npx jest`, the only CI this project has
// used to fail for any contributor who had not already run a build.
//
// Next.js never touches this path, so the two files coexist: the generated one
// keeps being regenerated by `next dev`/`next build`, and this one keeps the
// type-checker correct without it. Duplicate `/// <reference>` directives are
// idempotent.

/// <reference types="next" />
/// <reference types="next/image-types/global" />
