export const MAX_RETRIEVAL_FILE_IDS = 100
export const MAX_RETRIEVAL_QUERY_CHARS = 20_000
export const MAX_RETRIEVAL_SOURCE_COUNT = 10
export const MAX_DOCX_TEXT_CHARS = 2_000_000
export const MAX_LOCAL_DOCX_TEXT_CHARS = 500_000
export const MAX_FILE_ITEM_CHUNKS = 2048
